// <auto-generated />
using System;
using AeroTech.JetPay.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.JetPay.Persistence.Migrations
{
    [DbContext(typeof(JetPayDbContext))]
    partial class JetPayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Payment")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.JetPay.Domain.IdempotencyRecordAggregate.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("PaymentIntentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSessionId");

                    b.HasIndex("Operation", "Scope", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "Payment");
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.Entities.PaymentIntent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("AuthorizedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("CapturedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FundingReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("GuaranteeExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("GuaranteedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PaidUnappliedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentMethodOptionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PaymentSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("RefundedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenderType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSessionId");

                    b.HasIndex("Status");

                    b.ToTable("PaymentIntents", "Payment");
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.Entities.ProviderPaymentAttempt", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CallbackReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderProfileVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProviderTransactionRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ReversalExpectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UnknownSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("VerificationStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("VerifyDeadline")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PaymentIntentId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("Status", "ReversalExpectedAt");

                    b.ToTable("ProviderPaymentAttempts", "Payment");
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.PaymentSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AssuranceRequirement")
                        .HasColumnType("int");

                    b.Property<decimal>("CapturedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("GuaranteedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("InteractionMode")
                        .HasColumnType("int");

                    b.Property<long>("IssuerLegalEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("PayableInstructionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PayerType")
                        .HasColumnType("int");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<decimal>("RequiredAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SelectionMode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PayableInstructionId");

                    b.HasIndex("OrderId", "CommercialVersion");

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("PaymentSessions", "Payment");
                });

            modelBuilder.Entity("AeroTech.JetPay.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.JetPay.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.Entities.PaymentIntent", b =>
                {
                    b.HasOne("AeroTech.JetPay.Domain.PaymentSessionAggregate.PaymentSession", null)
                        .WithMany("Intents")
                        .HasForeignKey("PaymentSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.JetPay.Domain.PaymentSessionAggregate.ValueObjects.CustomerAction", "NextAction", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<DateTimeOffset?>("ExpiresAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NextActionExpiresAt");

                            b1.Property<string>("FormFields")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NextActionFormFields");

                            b1.Property<string>("HttpMethod")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("NextActionHttpMethod");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("NextActionType");

                            b1.Property<string>("Url")
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)")
                                .HasColumnName("NextActionUrl");

                            b1.HasKey("Id");

                            b1.ToTable("PaymentIntents", "Payment");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("NextAction");
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.Entities.ProviderPaymentAttempt", b =>
                {
                    b.HasOne("AeroTech.JetPay.Domain.PaymentSessionAggregate.Entities.PaymentIntent", null)
                        .WithMany("ProviderAttempts")
                        .HasForeignKey("PaymentIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.PaymentSession", b =>
                {
                    b.OwnsOne("AeroTech.JetPay.Domain.PaymentSessionAggregate.ValueObjects.PaymentInitiatorContext", "Initiator", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<long>("ActorId")
                                .HasColumnType("bigint")
                                .HasColumnName("InitiatorActorId");

                            b1.Property<string>("ActorType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("InitiatorActorType");

                            b1.Property<long?>("OfficeId")
                                .HasColumnType("bigint")
                                .HasColumnName("InitiatorOfficeId");

                            b1.Property<int>("SalesChannel")
                                .HasColumnType("int")
                                .HasColumnName("InitiatorSalesChannel");

                            b1.HasKey("Id");

                            b1.ToTable("PaymentSessions", "Payment");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Initiator")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.Entities.PaymentIntent", b =>
                {
                    b.Navigation("ProviderAttempts");
                });

            modelBuilder.Entity("AeroTech.JetPay.Domain.PaymentSessionAggregate.PaymentSession", b =>
                {
                    b.Navigation("Intents");
                });
#pragma warning restore 612, 618
        }
    }
}
